---
- hosts: all
  become: true
  tasks:
    - name: Change directory
      become: true
      shell: if [[ ! -d "/var/www/html/taotesting/data/tao/.git" ]]; then rm -rf /var/www/html/taotesting/data/tao && mv /var/www/html/taotesting/data/tao_ /var/www/html/taotesting/data/tao; fi

    - name: Checkout 'trialtesting' branch
      become: true
      shell: git checkout trialtesting
      args:
        chdir: /var/www/html/taotesting/data/tao

    - name: Pull latest changes
      become: true
      shell: git pull
      args:
        chdir: /var/www/html/taotesting/data/tao
