---
- hosts: all
  become: true
  tasks:
    - name: Change directory
      become: true
      shell: if [[ ! -d "/var/www/html/taotesting/data/tao/.git" ]]; then sudo rm -rf /var/www/html/taotesting/data/tao && sudo mv /var/www/html/taotesting/data/tao_ /var/www/html/taotesting/data/tao; fi

    #- name: Checkout 'trialtesting' branch
    #  become: true
    #  shell:
    #    cmd: sudo git checkout trialtesting
    #    chdir: /var/www/html/taotesting/data/tao

    - name: Get stuff from git
      git:
        repo: git:git@10.2.1.48:/opt/git/project.git
        dest: /var/www/html/taotesting/data/tao
        remote: "origin/trialtesting"
      become: true
      become_method: ansible.builtin.su

    #- name: Pull latest changes
    #  become: true
    #  shell:
    #    cmd: sudo git pull
    #    chdir: /var/www/html/taotesting/data/tao
